Repository az-digital/digital.arizona.edu, pull requests merged in 2020-10, with the labels that each got.

#13 Update to use the latest arizona-bootstrap assets
  docs/index.html
Labels: documentation, good first issue

#15 Feature/14 centrally managed typekit
  docs/index.html
Labels: documentation

#17 Closes #16 - Update home page documentation to improve clarity
  .gitignore
  docs/index.html
Labels: documentation

#20 use new env file instead of set-env
  .github/workflows/release.yml
Labels: hacktoberfest-accepted
